source 'https://rubygems.org'

ruby '2.1.2'
gem 'rails', '~> 4.2'
gem 'annotate'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bcrypt', '~> 3.1.7'

group :development do
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-byebug'
end

group :development, :test do
  gem 'capybara', '~> 2.4.4'
  gem 'launchy'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'spring'
end
